### ISSUE TITLE
#1 was accidentally locked instead of closed

### ISSUE THREAD

**Issue by cubrr** [HappyZombies/Circle#10]
Looks like #1 was accidentally locked. I recommend closing it instead.

![](http://i.imgur.com/a8LAWpB.png)

**Comment by cubrr** [comment]
This is what the issue's comment box looks like:

![image](https://cloud.githubusercontent.com/assets/6078228/8605082/5664c7b2-268b-11e5-90e1-effbd03fe01e.png)

**Comment by HappyZombies** [comment]
Ah ! Thanks for pointing that out :)

**Comment by cubrr** [comment]
Cheers! :smiley:

**Comment by HappyZombies** [comment]
I'm a little confused with something. If I remember, I merged 'Fixed Three Errors'  by electrocamel. 

That updated the file with the correct information. How come then , can Raijuu not see the updated version of the code and request to update it . . .Can he not see the updated version? Or is it for my eyes only?

**Comment by cubrr** [comment]
> How come then , can Raijuu not see the updated version of the code and request to update it 

Raijuu's local code will not change until he `git pull`s the changes from this repository.
