### ISSUE TITLE
Is it okay to have two files with main() class? 

### ISSUE THREAD

**Issue by HappyZombies** [HappyZombies/Circle#12]
Run_Circle & Run_Square both have a 
> public static void main(String[] args)

Is this okay? Is it okay for two files to have main? Or Is it better to just put the Run_Square code in the Run_Circle file, (which is the file that runs all the classes)

**Comment by ElectroCamel** [comment]
Well, yes, since they're independent from one another, they're just in the same directory. The problem starts if you have more main methods in the same class. In this case, if you run 
> java Run_Circle

it executes the main in Run_Circle.java , instead if you run
> java Run_Square

it runs the one in Run_Square.java.

**Comment by cubrr** [comment]
By the way, `main()` is not a _class_, it's a **method**. A _method_ is a **function** that's inside a class.
