### ISSUE TITLE
About Issues

### ISSUE THREAD

**Issue by HappyZombies** [HappyZombies/Circle#5]
Checking out how to display issues. 

From what I gathered, if someone wants to point out a problem, they 'Submit an issue' and people can discuss about it.

**Comment by cubrr** [comment]
Yes! Check out the labels on the sidebar to the right. You can [create new labels](https://github.com/HappyZombies/Circle/labels) as well! When working in collaboration, you can assign issues to users in the right sidebar.

**Comment by HappyZombies** [comment]
Very nice. I didn't even know that. Nice way to categorize issues. This is awesome!:

**Comment by cubrr** [comment]
Absolutely! If you're working on a project, the milestones are a great way to keep yourself on a deadline (or..not). For example, if you'd want to create an UI for your program, you could create issues (and label them as enhancements) related to creating an UI, then create a milestone for "New UI" and include all those issues in it!
